# Generated by Django 5.0.3 on 2024-03-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('QueenBee', 'QueenBee'), ('Soldier', 'Soldier')], default='QueenBee', max_length=20),
        ),
    ]
