# Generated by Django 5.0.3 on 2024-03-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_manager', '0002_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
