# Generated by Django 5.0.3 on 2024-03-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hive_manager', '0004_membership_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='task',
        ),
    ]
