# Generated by Django 5.0.3 on 2024-03-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_manager', '0005_remove_membership_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='task',
            field=models.ForeignKey(default='QueenBee', on_delete=django.db.models.deletion.CASCADE, to='hive_manager.task'),
        ),
    ]
