# Generated by Django 5.0.3 on 2024-03-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_manager', '0007_remove_membership_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('QueenBee', 'QueenBee'), ('Soldier', 'Soldier')], max_length=20),
        ),
    ]
