# Generated by Django 5.0.3 on 2024-04-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_manager', '0009_alter_membership_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
