# Generated by Django 5.0.3 on 2024-04-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_manager', '0010_rename_user_membership_user_alter_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='assigned_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hive_manager.task'),
        ),
    ]
