# Generated by Django 5.0.3 on 2024-04-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hive_manager', '0011_membership_assigned_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='assigned_task',
        ),
    ]
