# Generated by Django 4.2.11 on 2024-04-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_manager', '0011_alter_task_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('QueenBee', 'QueenBee'), ('Soldier', 'Soldier')], default='Member', max_length=20),
        ),
    ]
